# Generated by Django 4.0 on 2022-01-23 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(default='', max_length=5)),
                ('league', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('name', 'league')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_watchlisted', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('first_name', 'last_name', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('set', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('has_auto', models.BooleanField(default=False)),
                ('has_memorbilia', models.BooleanField(default=False)),
                ('in_collection', models.BooleanField(default=False)),
                ('is_watchlisted', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.player')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('title', 'player')},
            },
        ),
    ]
